### ISSUE TITLE
Profiles task list

### ISSUE THREAD

**Issue by SpoinkyNL** [SpoinkyNL/Artemis#78]
The [profiles branch](/SpoinkyNL/Artemis/tree/profiles_new) is starting to gain shape.
To keep my own sanity and provide a bit of a progress indicator, I'll keep track of a todo list right here.

Biggest thing still to do is dynamic properties, after that it's mainly polishing up the UI.

**Profiles**
- [x] Profile management per keyboard.
- [x] Fix bug when no effect is active (nothing shows)
- [x] Adjust margins for all keyboards
- [x] Create default profiles
- [x] UI - Removing profiles
- [x] UI - Automatically save profiles (_but not too often, IO operations are done_)
- [x] UI - Save last active profile
- [x] UI - General polish

**Layers**
- [x] Layers drawing (this is just one checkpoint but honestly 80% of the work ^^)
- [x] Layer dragging and resizing on keyboard (_needs to be calibrated for all keyboards, I only did K95 atm_).
- [x] Layer basic properties.
- [x] Layer conditions (_show only if x is happening in game_).
- [x] Layer dynamic properties (_change with depending on boost, ect.. mostly implemented but needs a UI_).
- [x] 'None' parameter for dynamic properties so they can be reset
- [x] Layer reordering
- [x] Layer grouping (_might leave this out until a later update_).
- [x] Preview on keyboard (_this kinda already happens, if the game you're configuring is running and the layer's conditions are met, but a toggle would be nice. Might leave this out until a later update_)
- [x] Contained colors
- [x] Grow animation
- [x] Layer type - GIF
- [x] Layer type - Mouse
- [x] Layer type - Headset
- [x] UI - Quick rename
- [x] UI - Delete layer in popup menu incorrectly disabled
- [x] UI - Closing without applying settings confirmation popup

**Games**
- [x] Rocket League
- [x] CS:GO
- [x] Dota 2
- [x] The Witcher 3
- [x] The Division
- [x] Overwatch

Most games could use a lot more data as well, but that's for another release.

**Comment by SpoinkyNL** [comment]
Just a tiny preview of the layer editor.
You can drag the layers around, resize them, add new ones ect.

![Layer editor](http://i.imgur.com/t1Bz3Z5.png)
